### ISSUE TITLE
Stops running

### ISSUE THREAD

**Issue by joaovdiasb** [yaegassy/coc-blade-formatter#1]
![image](https://user-images.githubusercontent.com/51106311/112147577-a2b75080-8bbb-11eb-8696-7b6fcacd6240.png)

Today this error appeared after the update, something changed?

**Comment by yaegassy** [comment]
@joaovdiasb 

Run `:CocCommand bladeFormatter.rebuild`.

(It will take a little while for the rebuild to finish.)

See: https://github.com/yaegassy/coc-blade-formatter#oniguruma-rebuild

**Comment by joaovdiasb** [comment]
Worked on windows after install **windows-build-tools** and **node-gyp**, and then run `:CocCommand bladeFormatter.rebuild`
Thanks for the library

**Comment by yaegassy** [comment]
Thank you for the detailed information. 🙇
