### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by shurizzle** [yaegassy/coc-blade-formatter#4]
It doesn't compile on node 16.

You can see the same problem here https://github.com/sass/node-sass/issues/3077

**Comment by yaegassy** [comment]
@shurizzle Thank you for reporting the issue. 🙇

"coc-blade-formatter" uses `blade-fromatter`.

I found a similar issue on blade-fomartter "issues". https://github.com/shufo/blade-formatter/issues/262

**Comment by shurizzle** [comment]
The problem is oniguruma package :)

**Comment by yaegassy** [comment]
blade-formatter has `vscode-oniguruma` as a dependency. :(

**Comment by shurizzle** [comment]
Just `blade-formatter` needs to update his `vscode-textmate` at 5.4.0. You can close this issue or keep it as a remainder :)
Thank you

**Comment by shurizzle** [comment]
If anybody is interested I fixed this in my vimrc like this https://github.com/shurizzle/vimmizzle/commit/308668dffadb2b6b617891ba01ecf6e9be7e888b
